# Generated by Django 4.0.2 on 2022-02-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
